neverrun_pw/config/routes.rb
Rails.application.routes.draw do
  root 'server#index', version: 'nwn1'

  get 'server/random', to: 'server#random'
  get ':version/servers/', to: 'server#index', as: 'servers'
  get ':version/servers/:id', to: 'server#show', as: 'server'
  get ':version/servers/:id/refresh_player_charts', to: 'server#refresh_player_charts'

  get ':version/servers/:server/last_hour', to: 'player_count#last_hour', as: 'player_count_last_hour'
  get ':version/servers/:server/popular', to: 'player_count#popular', as: 'player_count_popular'

  namespace :api do
    namespace :v1 do
      get 'servers', to: 'server#all'
      get 'servers/nwn1', to: 'server#nwn1', version: 'nwn1'
      get 'servers/nwn2', to: 'server#nwn2', version: 'nwn2'
      get 'servers/nwnee', to: 'server#nwnee', version: 'nwnee'

      get 'server/:address/:port_id',
          to: 'server#server_by_address',
          as: 'server_by_address',
          constraints: { address: /\d+\.\d+\.\d+\.\d+/,
                         port_id: /\d+/ }
      get 'server/:id', to: 'server#server_by_id', as: 'server_by_id'

      get 'players/:id/chart_data', to: 'players#chart_data', as: 'players_chart_data'
    end
  end
end

neverrun_pw/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

neverrun_pw/app/models/player_count.rb
class PlayerCount < ApplicationRecord
  belongs_to :server
end

neverrun_pw/app/models/server.rb
class Server < ApplicationRecord
  has_many :player_counts

  def self.create_server_from_api(server, version)
    addy, port = server[:server_address].split(':')
    create!(address: addy,
            port: port.to_i,
            build: server[:build_number],
            version: version,
            expansions: server[:expansions_mask],

            server_name: server[:server_name],
            server_description: server[:server_description],
            pwc_url: server[:pwc_url],

            module_name: server[:module_name],
            module_description: server[:module_description],
            module_url: server[:module_url],

            players: server[:active_player_count],
            players_max: server[:maximum_player_count],
            online: false,

            elc: server[:elc_enforced],
            gametype: server[:game_type],
            ilr: server[:ilr_enforced],
            level_min: server[:minimum_level],
            level_max: server[:maximum_level],
            localvault: server[:localvault],
            player_pause: server[:player_pause],
            private: server[:private_server],
            pvp: server[:pvp_level],
            single_party: server[:one_party_only])
  end
end

neverrun_pw/app/controllers/api/v1/players_controller.rb
class Api::V1::PlayersController < ApplicationController
  def chart_data
    counts = PlayerCount.where(server_id: params[:id]).order(timestamp: :desc).limit(30).pluck(:count)

    render json: {
        players: counts.reverse,
        popular: get_popular
    }
  end

  private

  def get_popular
    pcounts = PlayerCount.select(:count, :timestamp).where(server_id: params[:id]).all

    data = [
        {count: 0, sum: 0},
        {count: 0, sum: 0},
        {count: 0, sum: 0},
        {count: 0, sum: 0},
        {count: 0, sum: 0},
        {count: 0, sum: 0},
    ]

    pcounts.each do |s|
      case s.timestamp.hour
      when 0..3
        data[0][:count] += 1
        data[0][:sum] += s.count
      when 4..7
        data[1][:count] += 1
        data[1][:sum] += s.count
      when 8..11
        data[2][:count] += 1
        data[2][:sum] += s.count
      when 12..15
        data[3][:count] += 1
        data[3][:sum] += s.count
      when 16..19
        data[4][:count] += 1
        data[4][:sum] += s.count
      when 20..23
        data[5][:count] += 1
        data[5][:sum] += s.count
      end
    end

    { labels: ['12am-4am', '4am-8am', '8am-12pm', '12pm-4pm', '4pm-8pm', '8pm-12am'],
      data: data.map {|t| t[:count] == 0 ? 0 : t[:sum] / t[:count]} }
  end
end

neverrun_pw/app/controllers/api/v1/server_controller.rb
class Api::V1::ServerController < ApplicationController
  # API

  def all
    render json: Server.all
  end

  def servers_by_version(version)
    render json: Server.where(version: version)
                     .order(players: :desc)
                     .select(:id, :address, :port, :gametype, :players, :players_max, :server_name, :module_name, :online, :version)
  end

  def nwn1
    servers_by_version 1
  end

  def nwn2
    servers_by_version 2
  end

  def nwnee
    servers_by_version 3
  end

  def server_by_address
    render json: Server.where(address: params[:address], port: params[:port_id]).first
  end

  def server_by_id
    render json: Server.find(params[:id])
  end
end

neverrun_pw/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

neverrun_pw/app/controllers/server_controller.rb
class ServerController < ApplicationController
  before_action :current_server, only: [:show, :single, :refresh_player_charts]
  before_action :current_version, except: [:all, :single, :random]

  def index
    @servers = Server.where(version: @version).order(players: :desc)
  end

  def random
    @server = Server.order("RANDOM()").first
    @version = @server.version
  end

  def show
  end

  private

  def current_server
    @server = Server.find(params[:id])
  end

  def current_version
    @version = case params[:version].downcase
               when 'nwn1'
                 1
               when 'nwn2'
                 2
               when 'nwnee'
                 3
               end
  end

  def refresh_player_charts
    respond_to do |format|
      format.js
    end
  end
end

neverrun_pw/app/helpers/api/v1/players_helper.rb
module Api::V1::PlayersHelper
end

neverrun_pw/app/helpers/api/v1/server_helper.rb
module Api::V1::ServerHelper
end

neverrun_pw/app/helpers/application_helper.rb
module ApplicationHelper
end

neverrun_pw/app/helpers/server_helper.rb
require 'rails_rinku'

module ServerHelper
  def checkbox(predicate)
    if predicate
      content_tag(:div, '', class: 'far fa-check-square fa-lg')
    else
      content_tag(:div, '', class: 'far fa-square fa-lg')
    end
  end

  def gametype(type)
    case type
    when 0
      'Action'
    when 3
      'Role Play'
    when 4
      'Team'
    when 7
      'Social'
    when 9
      'PW Action'
    when 8
      'Alternative'
    when 1
      'Story'
    when 2
      'Story Lite'
    when 5
      'Melee'
    when 6
      'Arena'
    when 10
      'PW Story'
    when 11
      'Solo'
    when 12
      'Tech Support'
    else
      '<Unknown>'
    end
  end

  def markdown(text)
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                 autolink: true,
                                 tables: true)
    md.render(text)
  end

  def version_to_symbol(version)
    case version
    when 1
      :nwn1
    when 2
      :nwn2
    when 3
      :nwnee
    end
  end

  def version_to_s(version)
    case version
    when 1
      "NWN"
    when 2
      "NWN2"
    when 3
      "NWN:EE"
    end
  end

  def version_to_url(version)
    case version
    when 1
      "nwn1"
    when 2
      "nwn2"
    when 3
      "nwnee"
    end
  end
end

neverrun_pw/app/views/layouts/_footer.html.haml
.footer
  %ul
    %li
      By Source,
      %a{ href: "en.wikipedia.org/wiki/File:Neverwinter_Nights_cover.jpg",
          title: "Fair use of copyrighted material in the context of Neverwinter Nights" } Fair Use,
      %a{href: "https://en.wikipedia.org/w/index.php?curid=1954400" } Neverwinter Nights Box Art

    %li
      By Source,
      %a{ href: "en.wikipedia.org/wiki/File:Neverwinter_Nights_2_box_art.jpg",
          title: "Fair use of copyrighted material in the context of Neverwinter Nights 2" } Fair Use,
      %a{href: "https://en.wikipedia.org/w/index.php?curid=7501552" } Neverwinter Nights 2 Box Art

    %li
      By Source,
      %a{ href: "https://www.beamdog.com/assets/products/31860/original/Poster.png",
          title: "Fair use of copyrighted material in the context of Neverwinter Nights: Enhanced Edition" } Fair Use,
      %a{href: "https://www.beamdog.com/products/neverwinter-nights-enhanced-edition" } Neverwinter Nights: Enhanced Edition Box Art

neverrun_pw/app/views/layouts/_navbar.html.haml
%nav
  .game-toggle
    %a.game-toggle-btn{href: servers_path(:nwn1), class: "game-toggle-#{@version == 1 ? 'primary' : 'secondary'}"} NWN
    %a.game-toggle-btn{href: servers_path(:nwnee), class: "game-toggle-#{@version == 3 ? 'primary' : 'secondary'}"} NWN:EE
    %a.game-toggle-btn{href: servers_path(:nwn2), class: "game-toggle-#{@version == 2 ? 'primary' : 'secondary'}"} NWN2

  .nr-hamburger.dropdown
    %button#dropdownMenuButton{ type: 'button',
                                'data-toggle': 'dropdown',
                                'aria-haspopup': "true",
                                'aria-expanded': "false" }
      %i.fas.fa-bars
    .dropdown-menu.dropdown-menu-right
      %h6.dropdown-header
        Community
      %a.dropdown-item{href: 'http://neverwinternights.info/', target: '_blank'}
        Neverwinter Nights Info
      %a.dropdown-item{href: 'https://neverwintervault.org/', target: '_blank'}
        Neverwinter Vault

      .dropdown-divider

      %h6.dropdown-header
        Forums

      %a.dropdown-item{href: 'https://forums.beamdog.com/categories/neverwinter-nights', target: '_blank'}
        Beamdog

%img.nr-logo{alt: 'Logo', src: '/neverrun-logo.png'}

neverrun_pw/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NeverrunPw
    = csrf_meta_tags

    %link{ rel: "apple-touch-icon", sizes: "57x57", href: "/apple-icon-57x57.png" }
    %link{ rel: "apple-touch-icon", sizes: "60x60", href: "/apple-icon-60x60.png" }
    %link{ rel: "apple-touch-icon", sizes: "72x72", href: "/apple-icon-72x72.png" }
    %link{ rel: "apple-touch-icon", sizes: "76x76", href: "/apple-icon-76x76.png" }
    %link{ rel: "apple-touch-icon", sizes: "114x114", href: "/apple-icon-114x114.png" }
    %link{ rel: "apple-touch-icon", sizes: "120x120", href: "/apple-icon-120x120.png" }
    %link{ rel: "apple-touch-icon", sizes: "144x144", href: "/apple-icon-144x144.png" }
    %link{ rel: "apple-touch-icon", sizes: "152x152", href: "/apple-icon-152x152.png" }
    %link{ rel: "apple-touch-icon", sizes: "180x180", href: "/apple-icon-180x180.png" }
    %link{ rel: "icon", type: "image/png", sizes: "192x192" , href: "/android-icon-192x192.png" }
    %link{ rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" }
    %link{ rel: "icon", type: "image/png", sizes: "96x96", href: "/favicon-96x96.png" }
    %link{ rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" }
    %link{ rel: "manifest", href: "/manifest.json" }
    %meta{ name: "msapplication-TileColor", content: "#ffffff" }
    %meta{ name: "msapplication-TileImage", content: "/ms-icon-144x144.png" }
    %meta{ name: "theme-color", content: "#ffffff" }

    = stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.0.8/css/all.css'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container-fluid.fit-content
      .row
        .col-12
          = render partial: 'layouts/navbar'

      = yield

      %hr

      .row
        .col-12
          = render partial: 'layouts/footer'

neverrun_pw/app/views/server/_player_charts.html.haml
#playerCharts.server-players
  %h3= "Players: #{@server.players} / #{@server.players_max}"
  .row
    .col-lg-8
      %canvas#playerCountChart{height: '200px', width: "200px"}
    .col-lg-4
      %canvas#mostPopularTimesChart{height: '200px', width: "200px"}

  :javascript
    requestPlayerCharts(#{@server.id});

neverrun_pw/app/views/server/_server.html.haml
.container-fluid.server
  .row
    .col-12
      .server-header
        %h1.server-name= @server.server_name
        %h2.module-name= @server.module_name

  .row
    .col-xl-9
      = render partial: 'server/player_charts'


      .server-description
        %h3 Description

        - if @server.server_description.length > 0
          .description!= markdown @server.server_description

        - if @server.server_description.length > 0 and @server.module_description.length > 0
          %hr

        .description= auto_link @server.module_description, html: { target: '_blank' }

    .col-xl-3
      .server-info-table
        %table
          %tbody
            %tr
              %td Game
              %td= version_to_s @server.version
            %tr
              %td Type
              %td= gametype(@server.gametype)
            %tr
              %td Address
              %td= "#{@server.address}:#{@server.port}"
            %tr
              %td Levels
              %td= "#{@server.level_min} - #{@server.level_max}"

            %tr
              %td Password
              %td= checkbox(@server.private)

            %tr
              %td ELC
              %td= checkbox(@server.elc)

            %tr
              %td ILR
              %td= checkbox(@server.ilr)

            %tr
              %td Localvault
              %td= checkbox(@server.localvault)

            %tr
              %td One Party
              %td= checkbox(@server.single_party)

            %tr
              %td Player Pause
              %td.corner-br= checkbox(@server.player_pause)

:javascript
  setInterval(
    function() { refreshPlayerCharts(#{@server.version}, #{@server.id}); },
    60 * 1000);

neverrun_pw/app/views/server/index.html.haml
%div.server-table-top
  .legend-wrapper
    .online-legend
    %span.legend Online

  .legend-wrapper
    .offline-legend
    %span.legend Offline

  .legend-wrapper
    .private-legend
    %span.legend Private

  .server-filter
    %input.input-sm#serverFilterInput{type: "search", 'placeholder': "", 'aria-controls': "serverlist"}
    .server-filter-btn#serverFilterBtn
      %span.server-filter-icon.fa.fa-filter

%table.server-table.table.dataTable#serverTable{style:"width:100%", 'data-order': '[[ 1, "desc" ]]'}
  %thead
    %tr
      %th Server
      %th.align-right Players
      %th.align-right Address

:javascript
  initServerTable(#{@version});

neverrun_pw/app/views/server/random.html.haml
= render partial: 'server/server'

neverrun_pw/app/views/server/refresh_player_charts.js.haml
$('#playerCharts').html("#{escape_javascript(render 'server/player_charts')}");

neverrun_pw/app/views/server/show.html.haml
= render partial: 'server/server'